os: linux
dist: focal
language: python
addons:
  apt:
    update: true
    packages:
      - python3-scipy
      - gcc
      - gfortran
      - python3-dev
      - libopenblas-dev
      - liblapack-dev

jobs:
  fast_finish: true
  include:
    - python: '3.8'
      arch: s390x
    - python: '3.8'
      arch: ppc64le

before_install:
  - python3 -m pip install --upgrade pip

install:
  - pip3 install -r requirements-dev.txt
  - python3 setup.py install

script:
  - pytest